In [26]:
import pandas as pd
import numpy as np

df=pd.read_csv(r"C:\Users\sarve\Desktop\credit_card_fruda\fraudTrain.csv")
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [27]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [28]:
df['is_fraud'].value_counts()

0    1289169
1       7506
Name: is_fraud, dtype: int64

In [29]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load dataset
df = pd.read_csv(r"C:\Users\sarve\Desktop\credit_card_fruda\fraudTrain.csv")

# Parse datetime
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])
df['dob'] = pd.to_datetime(df['dob'])

# Create time-based features
df['hour'] = df['trans_date_trans_time'].dt.hour
df['day'] = df['trans_date_trans_time'].dt.day
df['weekday'] = df['trans_date_trans_time'].dt.weekday

# Calculate age
df['age'] = df['trans_date_trans_time'].dt.year - df['dob'].dt.year

# Encode gender: 'M' -> 0, 'F' -> 1
df['gender'] = df['gender'].map({'M': 0, 'F': 1})

# Label encode category and merchant
le_cat = LabelEncoder()
df['category'] = le_cat.fit_transform(df['category'])

le_merchant = LabelEncoder()
df['merchant'] = le_merchant.fit_transform(df['merchant'])

# Drop columns you won't use
df = df.drop(columns=[
    'Unnamed: 0', 'first', 'last', 'street', 'city', 'state', 'zip',
    'job', 'dob', 'trans_num', 'cc_num', 'trans_date_trans_time'
])

# Define features for modeling
feature_cols = [
    'amt', 'category', 'merchant', 'gender', 'lat', 'long',
    'merch_lat', 'merch_long', 'city_pop', 'age',
    'hour', 'day', 'weekday'
]

# Scale numeric features
scaler = StandardScaler()
df[feature_cols] = scaler.fit_transform(df[feature_cols])

# Final dataset
X = df[feature_cols].values
y = df['is_fraud'].values

# View a preview
print(pd.DataFrame(X, columns=feature_cols).head())
print(pd.Series(y).value_counts())


print(X)
print(y)

        amt  category  merchant    gender       lat      long  merch_lat  \
0 -0.407826  0.452853  0.851654  0.909206 -0.484420  0.657620  -0.494354
1  0.230039 -0.569266 -0.506880  0.909206  2.039120 -2.033870   2.078699
2  0.934149 -1.591384  0.234591 -1.099861  0.717754 -1.601537   0.902849
3 -0.158132 -1.080325  0.085302 -1.099861  1.515617 -1.590766   1.662886
4 -0.177094  0.708382 -0.228206 -1.099861 -0.023035  0.782279   0.026941

   merch_long  city_pop       age      hour       day   weekday
0    0.593864 -0.282589 -0.864629 -1.878145 -1.652258 -0.941975
1   -2.030341 -0.293670 -0.289333 -1.878145 -1.652258 -0.941975
2   -1.592323 -0.280406  0.631140 -1.878145 -1.652258 -0.941975
3   -1.621848 -0.287742  0.343492 -1.878145 -1.652258 -0.941975
4    0.841909 -0.293835 -0.749570 -1.878145 -1.652258 -0.941975
0    1289169
1       7506
dtype: int64
[[-0.40782607  0.45285278  0.85165441 ... -1.87814513 -1.65225774
  -0.94197487]
 [ 0.23003923 -0.56926552 -0.50688018 ... -1.87814513 -1.65225774
  -0.94197487]
 [ 0.93414872 -1.59138383  0.23459108 ... -1.87814513 -1.65225774
  -0.94197487]
 ...
 [ 0.22193025 -1.33585425  1.27464137 ... -0.11805205  0.6129742
   1.33266341]
 [ 0.02837499 -1.33585425  0.82677283 ... -0.11805205  0.6129742
   1.33266341]
 [-0.41200532 -1.33585425  0.13506474 ... -0.11805205  0.6129742
   1.33266341]]
[0 0 0 ... 0 0 0]

In [30]:
df.head()

,merchant,category,amt,gender,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud,hour,day,weekday,age
0,0.851654,0.452853,-0.407826,0.909206,-0.484420,0.657620,-0.282589,1325376018,-0.494354,0.593864,0,-1.878145,-1.652258,-0.941975,-0.864629
1,-0.506880,-0.569266,0.230039,0.909206,2.039120,-2.033870,-0.293670,1325376044,2.078699,-2.030341,0,-1.878145,-1.652258,-0.941975,-0.289333
2,0.234591,-1.591384,0.934149,-1.099861,0.717754,-1.601537,-0.280406,1325376051,0.902849,-1.592323,0,-1.878145,-1.652258,-0.941975,0.631140
3,0.085302,-1.080325,-0.158132,-1.099861,1.515617,-1.590766,-0.287742,1325376076,1.662886,-1.621848,0,-1.878145,-1.652258,-0.941975,0.343492
4,-0.228206,0.708382,-0.177094,-1.099861,-0.023035,0.782279,-0.293835,1325376186,0.026941,0.841909,0,-1.878145,-1.652258,-0.941975,-0.749570

In [31]:
df.to_csv('processed_fraud_data.csv', index=False)

In [32]:
dfp=pd.read_csv(r"C:\Users\sarve\Desktop\credit_card_fruda\processed_fraud_data.csv")
dfp.head()

,merchant,category,amt,gender,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud,hour,day,weekday,age
0,0.851654,0.452853,-0.407826,0.909206,-0.484420,0.657620,-0.282589,1325376018,-0.494354,0.593864,0,-1.878145,-1.652258,-0.941975,-0.864629
1,-0.506880,-0.569266,0.230039,0.909206,2.039120,-2.033870,-0.293670,1325376044,2.078699,-2.030341,0,-1.878145,-1.652258,-0.941975,-0.289333
2,0.234591,-1.591384,0.934149,-1.099861,0.717754,-1.601537,-0.280406,1325376051,0.902849,-1.592323,0,-1.878145,-1.652258,-0.941975,0.631140
3,0.085302,-1.080325,-0.158132,-1.099861,1.515617,-1.590766,-0.287742,1325376076,1.662886,-1.621848,0,-1.878145,-1.652258,-0.941975,0.343492
4,-0.228206,0.708382,-0.177094,-1.099861,-0.023035,0.782279,-0.293835,1325376186,0.026941,0.841909,0,-1.878145,-1.652258,-0.941975,-0.749570

In [48]:

dfp=dfp.drop('unix_time',axis=1)
detailed_stats = dfp.groupby('is_fraud').describe()

# Flatten the multi-level column index for better readability
detailed_stats.columns = ['_'.join(col).strip() for col in detailed_stats.columns.values]

# Save to CSV
detailed_stats.to_csv('processed_detailed_stats.csv', index=True)

print("Descriptive statistics saved to 'processed_detailed_stats.csv'")

Descriptive statistics saved to 'processed_detailed_stats.csv'

In [34]:
# from imblearn.over_sampling import SMOTE
# from imblearn.under_sampling import RandomUnderSampler
# from imblearn.under_sampling import TomekLinks
# from sklearn.model_selection import train_test_split
# import pandas as pd

# # Load your dataset (replace with your actual dataset)
# df = dfp

# # Separate features and labels
# X = df.drop('is_fraud', axis=1)
# y = df['is_fraud']

# # Define oversampling (SMOTE) and undersampling (Tomek Links)
# smote = SMOTE(random_state=42)
# tomek = TomekLinks()
# rus = RandomUnderSampler(random_state=42)

# # Apply SMOTE to oversample the minority class in the entire dataset
# #X_res_smote, y_res_smote = smote.fit_resample(X, y)

# # Now apply Tomek Links to clean the data
# X_res, y_res = tomek.fit_resample(X, y)
# X_rus,y_rus=rus.fit_resample(X_res,y_res)
# X_res, y_res = tomek.fit_resample(X_rus, y_rus)

# # Check the class distribution after both SMOTE and Tomek Links
# print("Original class distribution:")
# print(pd.Series(y).value_counts())

# print("Resampled class distribution:")
# print(pd.Series(y_res).value_counts())


import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import TomekLinks

# Load your preprocessed DataFrame
df = dfp

# Separate features and target
X = df.drop('is_fraud', axis=1)
y = df['is_fraud']

# Train-test split (important to avoid data leakage)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# Step 1: Apply SMOTE to oversample minority class
smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X_train, y_train)

# Step 2: Apply Tomek Links to clean borderline majority samples
tomek = TomekLinks()
X_res, y_res = tomek.fit_resample(X_smote, y_smote)

# Show class distributions
print("Original training set class distribution:")
print(y_train.value_counts())
print("\nAfter SMOTE + Tomek Links:")
print(pd.Series(y_res).value_counts())

Original training set class distribution:
0    902418
1      5254
Name: is_fraud, dtype: int64

After SMOTE + Tomek Links:
0    902418
1    798153
Name: is_fraud, dtype: int64

In [35]:
# Create a DataFrame of the resampled data
resampled_df = pd.DataFrame(X_res, columns=feature_cols)
resampled_df['is_fraud'] = y_res

# Show the first few rows
print(resampled_df.head())

        amt  category  merchant    gender       lat      long  merch_lat  \
0  0.807898  1.219442  1.244783  0.909206 -0.793671 -0.163998  -0.699426
1 -0.353683  0.197323  0.264449  0.909206 -1.355158 -0.478453  -1.285394
2 -0.139543  0.963912  0.000704  0.909206  0.742538  1.330478   0.759756
3  0.541112 -0.058206  1.294547  0.909206 -2.377045  0.611534  -2.239949
4  0.254304 -0.313736  1.548339  0.909206 -0.107041  0.093366  -0.161298

   merch_long  city_pop       age      hour       day   weekday  is_fraud
0   -0.150633 -0.280671 -0.116745  1.495367 -0.859427 -1.396903         0
1   -0.508276 -0.293292  0.976317 -0.118052 -1.538996  1.332663         0
2    1.325976 -0.278118  2.702204  0.615320  0.273189 -0.032120         0
3    0.630949  0.448514 -0.634511  1.495367 -1.652258  0.877736         0
4    0.061428 -0.293090 -0.174274  1.495367  0.159928 -0.941975         0

In [36]:
resampled_df.columns

Index(['amt', 'category', 'merchant', 'gender', 'lat', 'long', 'merch_lat',
       'merch_long', 'city_pop', 'age', 'hour', 'day', 'weekday', 'is_fraud'],
      dtype='object')

In [37]:
resampled_df.to_csv('resampled_fraud_data.csv', index=False)

In [46]:
# Descriptive statistics by fraud class
detailed_stats = resampled_df.groupby('is_fraud').describe()

# Flatten the multi-level column index for better readability
detailed_stats.columns = ['_'.join(col).strip() for col in detailed_stats.columns.values]

# Save to CSV
detailed_stats.to_csv('resampled_detailed_stats.csv', index=True)

print("Descriptive statistics saved to 'resampled_detailed_stats.csv'")

Descriptive statistics saved to 'resampled_detailed_stats.csv'